displayName=Book of the Dead Reminder
author=Jake
description=Reminds you when are missing only one thrall requirement (Book of the Dead, thrall runes, Arceuus spellbook)
tags=jake,arceuus,thrall,thralls,book of the dead,spell,spellbook,reminder,necromancy,resurrect,ghost,skeleton,zombie,rune,runes,lesser,superior,greater,casts,air,earth,fire,mind,death,blood,cosmic,staff,tome,rune pouch
plugins=com.bookofthedeadnotifier.BookOfTheDeadNotifierPlugin
build=standard
